Condense patient menu
dodoturkoz/COMP0066-Project pull request #29
Opened 2024-12-04 15:33 UTC by YandanaB

Just edits the flow of the patient.py file so that can see less options ("Edit Personal Info", "Record Mood of the Day", "Display Previous Moods", "Add Journal Entry", "Read Journal Entries", "Search Exercises", "Log out") if don't have clinician or these options with option of appointments if have clinician. With appointments see options "Book Appointment", "View Appointments",                             "Cancel Appointment", "Exit appointments"). Exit leads to patient menu. Patients with disabled accounts can login and logout only to see a message to contact admin. I still need to change the retry same action - plan to do this today. I have tested but can further rigorously test soon.

2024-12-04 17:07 UTC, davidve0206 requested changes

2024-12-04 22:20 UTC, YandanaB commented on modules/patient.py
> +                    log_out = input(
Yes, that makes sense. I am sorry about that. Have removed things on user accounts that are disabled.

2024-12-04 23:06 UTC, davidve0206 commented on modules/patient.py
> +                    log_out = input(
no need to apologise!

2024-12-05 12:00 UTC, philipcalderwood commented on modules/patient.py
> +                        # the patient had a clinician. Otherwise it would be log out.
is some of this logic made easier by moving to a system where 0 is always quit?

2024-12-05 12:03 UTC, philipcalderwood commented on modules/patient.py
> +                    # If there is no clinician, option 7 is logout
so keeping it at seven would simplify this into a single conditonal statement right?  `if (clinician_id): ...`

2024-12-05 12:11 UTC, philipcalderwood reviewed
Reading overall could we simplify approach by using quit as 0 and only having logout functionality from the main screen? Do we need a logout functionality at all? I think from this PR my vote is for 0 as quit throughout and scrap logout entirely for simplicity. Will put this to group.

2024-12-06 17:29 UTC, merged