Recent dates in setup tables
dodoturkoz/COMP0066-Project pull request #33
Opened 2024-12-04 18:46 UTC by YandanaB

Need to add more journal and mood entries. Should finish soon.

2024-12-05 10:02 UTC, philipcalderwood commented on database/setup.py
> +            minutes=random.randint(0, 60),
this could cause issues with appointment booking system change to on hour only (remove mins)

2024-12-05 10:02 UTC, philipcalderwood commented on database/setup.py
> +            hours=random.randint(0, 12),
standardise with appt times

2024-12-05 14:23 UTC, philipcalderwood requested changes
as per two comments in meeting - we agreed to standardise to appt times and remove minutes

2024-12-06 09:43 UTC, dodoturkoz approved these changes

2024-12-06 09:44 UTC, merged